var settings = {
  "RandomMonsterCommand": "!monster",
  "RandomMonsterEnabled": true,
  "RandomWeaponCommand": "!weapon",
  "RandomWeaponEnabled": true,
  "MonsterHunterGame": "World",
  "RandomQuestCommand": "!quest",
  "RandomQuestEnabled": true,
  "IncludeVillage": false,
  "IncludeHub": true,
  "IncludeLowRank": false,
  "IncludeHighRank": true,
  "IncludeSmallMonsters": false,
  "MinimumStar": "1",
  "IncludeDeliverQuests": false,
  "IncludeHuntQuests": true,
  "IncludeSlayQuests": true,
  "IncludeCaptureQuests": true,
  "IncludeNonMonster": false,
  "IncludeArenas": false,
  "IncludeChallenges": false,
  "IncludeEvents": false
};